### ISSUE TITLE
elpers.go:49:27: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by chrismalek** [Clivern/Poodle#20]
Tried installing from source

```sh
go get github.com/Clivern/Poodle        
# github.com/clivern/poodle/core/util
../code/go/src/github.com/clivern/poodle/core/util/helpers.go:49:27: multiple-value uuid.NewV4() in single-value context


```

```sh
go version
go version go1.14.5 darwin/amd64


```

**Comment by Clivern** [comment]
I removed that function and uuid pkg. you can use the latest version `go get github.com/clivern/poodle`. It should work now.

`uuid.Must(uuid.NewV4(), nil)` used to be multiple-value context, then got changed to a single-value context. so it is probably picking an old version.
