### ISSUE TITLE
Default body behaviour doesn't appear valid

### ISSUE THREAD

**Issue by m0un10** [Clivern/Poodle#22]
**Describe the bug**
I suspect that when `body` is not set it defaults to `{\"name\":\"{$name}\",\"type\":\"{$type:default}\"}` instead of `""` which is unintuitive because a user will receive a prompt like below which won't make sense.

```
$name* (default=''): blah█
$type (default='default'): blah█
```

To reproduce

```
[Main]
  id = "OMITTED"
  name = "OMITTED"
  description = "OMITTED"
  timeout = "30s"
  service_url = "OMITTED"
  headers = [["Content-Type", "application/json"]]

[Security]
  scheme = "basic"
  [Security.Basic]
    username = "OMITTED"
    password = "OMITTED"

[[Endpoint]]
  id = "OMITTED"
  name = "OMITTED"
  method = "get"
  uri = "/OMITTED"
```

In order to workaround I just add `body = ""`.

**Development or production environment**
 - Mac OS
 - Go 1.14.3

**Additional context**

Great tool so far. I almost raised a ticket about basic auth problems but turned out it was fixed in the 0.2.0 release from 6 hours ago!! Talk about good timing :)

**Comment by Clivern** [comment]
Hello @m0un10,

That's a good catch 👍, since i use https://github.com/Clivern/Poodle/blob/master/core/model/service.go#L68 during service toml file encoding, if body or any property is omitted, it won't override the one in the code. will do a fix for it!
